# Generated by Django 4.1.7 on 2023-03-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_adding', models.TextField(blank=True, max_length=9999, null=True, verbose_name='Текст для модерації')),
                ('img_for_adding', models.CharField(blank=True, max_length=500, null=True, verbose_name='Зоображення для додавання')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='По батькові')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('citizenship', models.CharField(blank=True, max_length=64, null=True, verbose_name='Громадянство')),
                ('passport', models.CharField(blank=True, max_length=64, null=True, verbose_name='Паспорт')),
                ('individual_identification_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Індитифікаційний код')),
                ('place_of_birthday', models.CharField(blank=True, max_length=128, null=True, verbose_name='Місце народження')),
                ('place_of_living', models.CharField(blank=True, max_length=500, null=True, verbose_name='Місце проживання')),
                ('additional_info', models.TextField(blank=True, max_length=9999, null=True, verbose_name='Додаткова інформація')),
                ('source', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Джерело')),
                ('rank', models.CharField(blank=True, max_length=64, null=True, verbose_name='Військове звання')),
                ('job_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Посада')),
                ('military_unit', models.CharField(blank=True, max_length=256, null=True, verbose_name='Військова частина')),
                ('type_of_army', models.CharField(blank=True, max_length=500, null=True, verbose_name='Рід військ')),
                ('military_from', models.CharField(blank=True, max_length=64, null=True, verbose_name='Місце знаходження військової частини')),
                ('сommander', models.CharField(blank=True, max_length=64, null=True, verbose_name='Командир')),
                ('status_person', models.CharField(choices=[('ALIVE', 'Alive'), ('CAPTIVITY', 'Captivity'), ('DIE', 'Die'), ('MISSING_PERSON', 'Missing person')], default='DIE', max_length=32, verbose_name='Статус')),
                ('place_where_accident', models.CharField(blank=True, max_length=500, null=True, verbose_name='Місце інцидету')),
                ('data_when_accident', models.DateField(blank=True, default=None, null=True, verbose_name='Дата інциденту')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни')),
                ('post_status', models.CharField(choices=[('FORCHECK', 'For check'), ('DELETED', 'Deleted'), ('PROCESSING', 'Processing'), ('FOR_MODERATION', 'For moderation'), ('PUBLISHED', 'Published')], default='FOR_MODERATION', max_length=32, verbose_name='Статус поста')),
                ('publish_status', models.CharField(choices=[('PUBLISHED', 'Published'), ('NOTPUBLISHED', 'Not published')], default='NOTPUBLISHED', max_length=32, verbose_name='Статус публікації')),
                ('take_task', models.CharField(default='not taken', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonTypeSocialNetworkChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='Тип')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoursePersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_images', to='diap.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Посилання на текст')),
                ('text_from', models.CharField(max_length=128, verbose_name='Звідки текст (Домен)')),
                ('text', models.TextField(verbose_name='Текст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='diap.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=128, verbose_name='Посилання на профіль')),
                ('profile_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Логін профілю')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='diap.person')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diap.persontypesocialnetworkchoices', verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPlaceWhereHeWas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128, verbose_name='Місця дислокації')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_where_he_was', to='diap.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diap.person')),
            ],
        ),
    ]
