# Generated by Django 4.1.7 on 2023-03-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='сommander',
            new_name='commander',
        ),
    ]
