# Generated by Django 4.1.7 on 2023-03-22 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diap', '0002_rename_сommander_person_commander'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News/%Y/%m/%d', verbose_name='Картинка')),
                ('published', models.BooleanField(default=False, verbose_name='Статус публікації')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час зміни')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_news_dead', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новини з втратами РФ',
                'verbose_name_plural': 'Новини з втратами РФ',
            },
        ),
    ]
