# Generated by Django 4.1.7 on 2023-03-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0005_person_rank_choice_person_type_of_army_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('url', models.URLField(verbose_name='Посилання')),
                ('image', models.ImageField(upload_to='partner/%Y/%m/%d')),
                ('published', models.BooleanField(default=False, verbose_name='Статус публікації')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
