# Generated by Django 4.1.7 on 2023-03-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0006_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type_of_army_choice',
            field=models.CharField(blank=True, choices=[('Сухопутные войска', 'Сухопутные войска'), ('Воздушно-космические силы', 'Воздушно-космические силы'), ('Военно-Морской Флот', 'Военно-Морской Флот'), ('Ракетные войска стратегического назначения', 'Ракетные войска стратегического назначения'), ('Воздушно-десантные войска', 'Воздушно-десантные войска'), ('Войска национальной гвардии Российской Федерации', 'Войска национальной гвардии Российской Федерации'), ('ЧВК', 'ЧВК')], max_length=64, null=True, verbose_name='Рід військ - '),
        ),
    ]
