# Generated by Django 4.1.7 on 2023-04-17 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0009_alter_person_type_of_army_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День народження'),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday_month',
            field=models.CharField(blank=True, choices=[('1', 'Січень | Январь'), ('2', 'Лютий | Февраль'), ('3', 'Березень | Март'), ('4', 'Квітень | Апрель'), ('5', 'Травень | Май'), ('6', 'Червень | Июнь'), ('7', 'Липень | Июль'), ('8', 'Серпень | Август'), ('9', 'Вересень | Сентябрь'), ('10', 'Жовтень | Октябрь'), ('11', 'Листопад | Ноябрь'), ('12', 'Грудень | Декабрь')], max_length=64, null=True, verbose_name='Місяць народження'),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)], verbose_name='Рік народження'),
        ),
    ]
