# Generated by Django 4.1.7 on 2023-04-17 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0010_person_birthday_day_person_birthday_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data_when_accident_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День інциденту'),
        ),
        migrations.AddField(
            model_name='person',
            name='data_when_accident_month',
            field=models.CharField(blank=True, choices=[('1', 'Січень | Январь'), ('2', 'Лютий | Февраль'), ('3', 'Березень | Март'), ('4', 'Квітень | Апрель'), ('5', 'Травень | Май'), ('6', 'Червень | Июнь'), ('7', 'Липень | Июль'), ('8', 'Серпень | Август'), ('9', 'Вересень | Сентябрь'), ('10', 'Жовтень | Октябрь'), ('11', 'Листопад | Ноябрь'), ('12', 'Грудень | Декабрь')], max_length=64, null=True, verbose_name='Місяць інциденту'),
        ),
        migrations.AddField(
            model_name='person',
            name='data_when_accident_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)], verbose_name='Рік інциденту'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_rip',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Місце поховання'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_rip_date_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День поховання'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_rip_date_month',
            field=models.CharField(blank=True, choices=[('1', 'Січень | Январь'), ('2', 'Лютий | Февраль'), ('3', 'Березень | Март'), ('4', 'Квітень | Апрель'), ('5', 'Травень | Май'), ('6', 'Червень | Июнь'), ('7', 'Липень | Июль'), ('8', 'Серпень | Август'), ('9', 'Вересень | Сентябрь'), ('10', 'Жовтень | Октябрь'), ('11', 'Листопад | Ноябрь'), ('12', 'Грудень | Декабрь')], max_length=64, null=True, verbose_name='Місяць поховання'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_rip_date_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)], verbose_name='Рік поховання'),
        ),
    ]
