# Generated by Django 4.1.7 on 2023-04-18 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0012_alter_person_birthday_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday_day',
            field=models.CharField(blank=True, choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=64, null=True, verbose_name='День народження'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday_month',
            field=models.CharField(blank=True, choices=[('01', 'Січень | Январь'), ('02', 'Лютий | Февраль'), ('03', 'Березень | Март'), ('04', 'Квітень | Апрель'), ('05', 'Травень | Май'), ('06', 'Червень | Июнь'), ('07', 'Липень | Июль'), ('08', 'Серпень | Август'), ('09', 'Вересень | Сентябрь'), ('10', 'Жовтень | Октябрь'), ('11', 'Листопад | Ноябрь'), ('12', 'Грудень | Декабрь')], max_length=64, null=True, verbose_name='Місяць народження'),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_when_accident_day',
            field=models.CharField(blank=True, choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=64, null=True, verbose_name='День смерті'),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_when_accident_month',
            field=models.CharField(blank=True, choices=[('01', 'Січень | Январь'), ('02', 'Лютий | Февраль'), ('03', 'Березень | Март'), ('04', 'Квітень | Апрель'), ('05', 'Травень | Май'), ('06', 'Червень | Июнь'), ('07', 'Липень | Июль'), ('08', 'Серпень | Август'), ('09', 'Вересень | Сентябрь'), ('10', 'Жовтень | Октябрь'), ('11', 'Листопад | Ноябрь'), ('12', 'Грудень | Декабрь')], max_length=64, null=True, verbose_name='Місяць смерті'),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_when_accident_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)], verbose_name='Рік смерті'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_rip_date_day',
            field=models.CharField(blank=True, choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8'), ('09', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=64, null=True, verbose_name='Дата поховання'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_rip_date_month',
            field=models.CharField(blank=True, choices=[('01', 'Січень | Январь'), ('02', 'Лютий | Февраль'), ('03', 'Березень | Март'), ('04', 'Квітень | Апрель'), ('05', 'Травень | Май'), ('06', 'Червень | Июнь'), ('07', 'Липень | Июль'), ('08', 'Серпень | Август'), ('09', 'Вересень | Сентябрь'), ('10', 'Жовтень | Октябрь'), ('11', 'Листопад | Ноябрь'), ('12', 'Грудень | Декабрь')], max_length=64, null=True, verbose_name='Місяць поховання'),
        ),
    ]
