# Generated by Django 4.1.7 on 2023-04-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0013_alter_person_birthday_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='task_deleted',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Видалив'),
        ),
        migrations.AddField(
            model_name='person',
            name='task_processing',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Доопрацювання'),
        ),
        migrations.AddField(
            model_name='person',
            name='task_published',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Опублікував'),
        ),
    ]
