# Generated by Django 4.1.7 on 2023-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0014_person_task_deleted_person_task_processing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='task_for_check',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='На перевірці'),
        ),
    ]
