# Generated by Django 4.1.7 on 2023-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0015_person_task_for_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='task_deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='task_for_check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='task_processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='task_published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
