# Generated by Django 4.1.7 on 2023-04-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0017_alter_person_rank_alter_person_rank_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Повідомлення про помилку', 'verbose_name_plural': 'Повідомлення про помилку'},
        ),
        migrations.AddField(
            model_name='soursepersonimage',
            name='main_image',
            field=models.BooleanField(default=False, verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_status',
            field=models.CharField(choices=[('FORCHECK', 'For check'), ('DELETED', 'Deleted'), ('PROCESSING', 'Processing'), ('FOR_MODERATION', 'For moderation'), ('PUBLISHED', 'Published'), ('INCOMING', 'Incoming')], default='FOR_MODERATION', max_length=32, verbose_name='Статус поста'),
        ),
    ]
