# Generated by Django 4.1.7 on 2023-04-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0018_alter_callback_options_soursepersonimage_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soursepersonimage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='personimage',
            name='main_image',
            field=models.BooleanField(default=False, verbose_name='Головне фото'),
        ),
    ]
