# Generated by Django 4.1.7 on 2023-04-26 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diap', '0019_remove_soursepersonimage_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='post_status',
            field=models.CharField(choices=[('FORCHECK', 'For check'), ('DELETED', 'Deleted'), ('PROCESSING', 'Processing'), ('FOR_MODERATION', 'For moderation'), ('PUBLISHED', 'Published'), ('INCOMING', 'Incomings')], default='FOR_MODERATION', max_length=32, verbose_name='Статус поста'),
        ),
        migrations.CreateModel(
            name='ImportantNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, verbose_name='Назва')),
                ('text', models.CharField(blank=True, max_length=256, verbose_name='Текст')),
                ('span_date', models.CharField(blank=True, help_text='Приклад вводу 17/04/2023 13:15', max_length=256, verbose_name='Дата публікації')),
                ('url_news', models.URLField(blank=True, help_text='Посилання на новину', verbose_name='Url публікації')),
                ('news_name', models.CharField(blank=True, max_length=256, verbose_name='Звідки новина')),
                ('image', models.ImageField(upload_to='ImportantDead/%Y/%m/%d', verbose_name='Картинка')),
                ('published', models.BooleanField(default=False, verbose_name='Статус публікації')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час зміни')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_important_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Важливі новини',
                'verbose_name_plural': 'Важливі новини',
            },
        ),
    ]
