# Generated by Django 4.1.7 on 2023-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0020_alter_person_post_status_importantnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantnews',
            name='news_name',
            field=models.CharField(max_length=256, verbose_name='Звідки новина'),
        ),
        migrations.AlterField(
            model_name='importantnews',
            name='span_date',
            field=models.CharField(help_text='Приклад вводу 17/04/2023 13:15', max_length=256, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='importantnews',
            name='text',
            field=models.CharField(max_length=256, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='importantnews',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='importantnews',
            name='url_news',
            field=models.URLField(help_text='Посилання на новину', verbose_name='Url публікації'),
        ),
    ]
