# Generated by Django 4.1.7 on 2023-04-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0021_alter_importantnews_news_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantnews',
            name='user',
        ),
    ]
