# Generated by Django 4.1.7 on 2023-04-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('diap', '0022_remove_importantnews_user'),
    ]

    operations = [
    ]
