# Generated by Django 4.1.7 on 2023-05-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0025_alter_person_birthday_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram user id')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Прізвище')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='Username')),
                ('language', models.CharField(choices=[('RU', 'Русский язык'), ('EN', 'English language'), ('UK', 'Українська мова')], default='UK', max_length=2, verbose_name='Мова користувача')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни')),
            ],
            options={
                'verbose_name': 'Користувач Telegram',
                'verbose_name_plural': 'Користувачі Telegram',
            },
        ),
    ]
