# Generated by Django 4.1.7 on 2023-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0029_alter_person_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='post_status',
            field=models.CharField(choices=[('INCOMING', 'Incomings'), ('FOR_MODERATION', 'For moderation'), ('FORCHECK', 'For check'), ('PUBLISHED', 'Published'), ('PROCESSING', 'Processing'), ('DELETED', 'Deleted'), ('BEFORE_2022', 'Died before 2022')], default='FOR_MODERATION', max_length=32, verbose_name='Статус поста'),
        ),
    ]
