version: "3.11"

services:
  web:
    build: 
      context: ../
    command: sh /code/production-docker-entrypoint.sh
    env_file:
      - env-staging
    volumes:
      - "media_volume_staging:/code/media:rw"
      - "static_volume_staging:/code/staticfiles:rw"
    depends_on:
      - poternet_db

  poternet_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=war_crime_user
      - POSTGRES_PASSWORD=3232322ddd
      - POSTGRES_DB=war_crime
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data/
    ports:
      - 5433:5432

  nginx:
    build: 
      context: ../nginx
    depends_on:
      - web  
    ports:
      - 8080:80
    volumes:
      - "media_volume_staging:/var/www/html/media:ro"
      - "static_volume_staging:/var/www/html/static:ro"

volumes:
  postgres_data_staging:
  media_volume_staging:
  static_volume_staging:
